### ISSUE TITLE
Yaml pre compiled deserialize improvement

### ISSUE THREAD

**Issue by rube200** [hadashiA/VYaml#118]
Hello there,
i was messing around with transpilerm and IL, and found out that `switch` in `Deserialize` could be improved.

This code:
https://github.com/hadashiA/VYaml/blob/aa786ee098dec28f66839c5df2df41e54172e2e9/VYaml.SourceGenerator/Emitter.cs#L425-L426
could be replaced to `codeWriter.AppendLine("goto default"); `

As you can see by this iamge (IL code), it created the same code again and again instead of jumping for default labek
![image](https://github.com/user-attachments/assets/65eb4365-f5fc-4579-84b7-102c1542680b)

**Comment by hadashiA** [comment]
Thanks for pointing this out.
I would like to understand the issue clearly - is it a question of increasing the amount of code?
My understanding is that it doesn't seem to affect the speed of execution, is my perception correct?

**Comment by rube200** [comment]
Yes, this issue should not affect execution speed.
This issue just affect compiled file sizes per field

**Comment by hadashiA** [comment]
Ok, personally I don't think it's that big a deal, give me a pull request and I'll merge it in.

**Comment by hadashiA** [comment]
Merged #119
