### ISSUE TITLE
Uri型が読み込めない

### ISSUE THREAD

**Issue by Freeesia** [hadashiA/VYaml#19]
組み込みのUriFormatterの以下の部分で`ReadOnlySpan<byte>`を`ToString()`で文字列化しているため、読み込んだUri文字列ではなく型名が文字列になり、不正なUriとして読み込まれます。

https://github.com/hadashiA/VYaml/blob/master/VYaml.Core/Serialization/Formatters/UriFormatter.cs#L20

手元ではデシリアライズするプロパティをUri型ではなくstring型にして回避してます。

**Comment by hadashiA** [comment]
@Freeesia  #24 で修正しました。ご報告ありがとうございます!

**Comment by Freeesia** [comment]
@hadashiA 
対応ありがとうございます。リリースされたら試してみます。
