### ISSUE TITLE
配列を書き込んだあとのMapキーの書き出しインデントが一つ手前にずれる

### ISSUE THREAD

**Issue by Freeesia** [hadashiA/VYaml#20]
以下のようなクラスHogeをymlに出力するとProps2のインデントがずれます。
```cs
[YamlObject]
partial class Hoge
{
    public Fuga Fuga { get; set; }
}
[YamlObject]
partial class Fuga
{
    public string[] Props1 { get; set; }
    public string[] Props2 { get; set; }
}
```
```yml
fuga: 
  props1: 
  - a
  - b
props2: 
- c
- d
```

以下の箇所でインデントの増減が一致していないことが原因かと思われます。
https://github.com/hadashiA/VYaml/blob/master/VYaml.Core/Emitter/Utf8YamlEmitter.cs#L114
https://github.com/hadashiA/VYaml/blob/master/VYaml.Core/Emitter/Utf8YamlEmitter.cs#L185

**Comment by hadashiA** [comment]
@Freeesia #25 で修正しました。厄介な不具合だと思うので教えていただいて助かります

**Comment by Freeesia** [comment]
@hadashiA 
こちらも対応ありがとうございました。
かなり無理矢理回避してたので助かります。
