### ISSUE TITLE
Unity issue with CS0570

### ISSUE THREAD

**Issue by Whimsyduke** [hadashiA/VYaml#27]
I get a issue in Unity with the error message:
Assets\VYaml\Runtime\Parser\Utf8YamlTokenizer.cs(38,30): error CS0570: 'T' is not supported by the language
I use 2022.2.18f1 and 2021.3.24f1 test and got the same error

**Comment by hadashiA** [comment]
@Whimsyduke Please check your player settings.
Perhaps the API Compatibility Level should be .NET standard, not .NET 4.x.

**Comment by Whimsyduke** [comment]
Yes, its this reason. I found it in other place and fogot to replay,sorry.
