### ISSUE TITLE
deserializer isn't distinguish long and double type.

### ISSUE THREAD

**Issue by jinialadin1** [hadashiA/VYaml#52]
Hello, I'm trying to parsing the Unity Scene file using this library.

![image](https://github.com/hadashiA/VYaml/assets/16120321/ee5f6fe2-f606-40ff-a3e8-f5568b4cfcbe)

left is the original Image and right side is the deserialized and serialized by the library

As you can see in the above image, `fileID` is **long** type as I believe, but the deserializer make it as **double** type.
fileID was `1058064039477804610` but changed to `1.0580640394778E+18`.

So when I serialize it again, the scene file would be corrupted due to those issue. Could you fix it? Thank you so much.

I used this library like below code
``` CS
    var memory = new ReadOnlyMemory<byte>(Encoding.UTF8.GetBytes(sceneString));
    var collection = YamlSerializer.DeserializeMultipleDocuments<dynamic>(memory).ToList();
    ...
``` 

would it be possible to customize deserialize only for the type `IYamlFormatter<KeyValuePair<TKey, TValue>>` when TKey is string and it is `fileID` ?

**Comment by hadashiA** [comment]
Helo, tanks for the report.

Fixed in #55
