### ISSUE TITLE
Is it possible to preset a UnityResolvers in VYaml.Unity

### ISSUE THREAD

**Issue by MonoLogueChi** [hadashiA/VYaml#91]
In some cases, I will need to serialize and deserialize Unity types, such as Vector3, Color, etc. Although I implemented part of it myself, I would like to have a UnityResolvers that contains commonly used Unity types and is automatically enabled when using Unity. Just like MessagePack-CSharp.

**Comment by MonoLogueChi** [comment]
Do you have any plans to implement this feature?
I implemented part of it myself, can I PR to the warehouse? Is there anything I need to pay attention to when submitting a PR?
![image](https://github.com/hadashiA/VYaml/assets/26868745/19e726a6-8176-4897-8d07-c665aa3c888e)

**Comment by hadashiA** [comment]
@MonoLogueChi Thanks so much. PR is welcome.
I don't have a detailed contribution rule. If there is no problem, I would like to adopt it.
( However, after merging your commits, I may have to rework them.

**Comment by MonoLogueChi** [comment]
@hadashiA 

Okay, I'll try not to break the original code and keep the style consistent.

The serialization I implemented is similar to the style of MessagePack-CSharp, that is

- `Color` `Color32` -> `[r,g,b,a]`
- `Vector3` `Vector3Int` -> `[x,y,z]`

This will not only make it easier to edit the configuration file, but will also be more efficient.

**Comment by MonoLogueChi** [comment]
If I need to create a tool class and place some public code, where should I create it? The code is similar to this

```cs
    internal static class Utils
    {
        public static void WriteFloatArrayWithFlowStyle(ref Utf8YamlEmitter emitter, IEnumerable<float> value,
            YamlSerializationContext context)
        {
            emitter.BeginSequence(SequenceStyle.Flow);
            foreach (var f in value) emitter.WriteFloat(f);
            emitter.EndSequence();
        }

        public static void WriteByteArrayWithFlowStyle(ref Utf8YamlEmitter emitter, IEnumerable<byte> value,
            YamlSerializationContext context)
        {
            emitter.BeginSequence(SequenceStyle.Flow);
            foreach (var b in value) emitter.WriteInt32(b);
            emitter.EndSequence();
        }

        public static void WriteIntArrayWithFlowStyle(ref Utf8YamlEmitter emitter, IEnumerable<int> value,
            YamlSerializationContext context)
        {
            emitter.BeginSequence(SequenceStyle.Flow);
            foreach (var i in value) emitter.WriteInt32(i);
            emitter.EndSequence();
        }
    }
```

**Comment by MonoLogueChi** [comment]
I have been sorting out the code recently and found that instead of merging it into VYaml, creating a VYaml.UnityResolvers project myself may be a better choice. The reasons are as follows

- Will affect VYaml .net side testing
- Creating UnityResolvers does not require modifying VYaml code
- The serialization and deserialization methods are written according to my habits and may not be recognized by everyone, causing the VYaml project to be affected.

**Comment by hadashiA** [comment]
Thanks for the good work !

VYaml would like to focus on Unity.
I would like to add similar functionality to the main repo using your code as a reference :)

**Comment by hadashiA** [comment]
I decided to port it to the main repo. #106

**Comment by hadashiA** [comment]
I'll close this issue now that I've implemented most of the Unity formatters.
If there's anything else you need, I'd be happy to take on additional PRs. Thanks.
